### ISSUE TITLE
Spotify: enable secure playback

### ISSUE THREAD

**Issue by vincentbernat** [flathub/com.gitlab.ColinDuquesnoy.MellowPlayer#1]
Hey!

I've just tried this Flatpak and when using Spotify, I get "Enable secure playback in your browser.
Visit the Spotify support site to see how." I suppose the embedded browser does not have the DRM bits enabled.

**Comment by ColinDuquesnoy** [comment]
Hello,

Indeed, widevine plugin is not included in the flatpak. For now there is a [documented workaround](https://mellowplayer.readthedocs.io/en/stable/users/install.html#widevine-support-in-flatpak) to use the [system plugin](https://mellowplayer.readthedocs.io/en/stable/users/install.html#widevine-support).

I will dig in to see if I can included it so you don't have to use a flatpak override.

**Comment by ColinDuquesnoy** [comment]
Correct me if I'm wrong but I don't think I can legally redistribute the widevine DRM plugin, the google license looks quite clear:

```
"Google Inc. and its affiliates ("Google") own all legal right, title and
interest in and to the content decryption module software ("Software") and
related documentation, including any intellectual property rights in the
Software. You may not use, modify, sell, or otherwise distribute the Software
without a separate license agreement with Google.  The Software is not open
source software.

If you are interested in licensing the Software, please contact
widevine@google.com.
```

But I've simplified the installation script to a one liner:

```bash
curl -s "https://gitlab.com/ColinDuquesnoy/MellowPlayer/-/raw/master/scripts/install-widevine.sh" | bash
```
